"use client";

import { useEffect } from "react";

const norm=(s:string)=>s.normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/ı/g,"i").toLocaleLowerCase("tr-TR").replace(/\s+/g," ").trim();
const bekle=(ms:number)=>new Promise<void>(r=>window.setTimeout(r,ms));
const alan=(metin:string,ad:string)=>{const re=new RegExp(`(?:^|\\n)${ad.replace(/[.*+?^${}()|[\\]\\]/g,"\\$&")}:\\s*([^\\n]+)`,`i`);const v=metin.match(re)?.[1]?.trim()||"";return v==="—"?"":v;};
function alanInput(baslik:string,scope:ParentNode=document){const hedef=norm(baslik.replace(/\*/g,""));const spans=Array.from(scope.querySelectorAll<HTMLSpanElement>("span"));const s=spans.find(x=>norm((x.textContent||"").replace(/\*/g,""))===hedef);return (s?.parentElement?.querySelector("input,textarea")||null) as HTMLInputElement|HTMLTextAreaElement|null;}
function nativeDeger(el:HTMLInputElement|HTMLTextAreaElement,v:string){const proto=el instanceof HTMLTextAreaElement?HTMLTextAreaElement.prototype:HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(proto,"value")?.set?.call(el,v);el.dispatchEvent(new Event("input",{bubbles:true}));el.dispatchEvent(new Event("change",{bubbles:true}));}
async function metinDoldur(baslik:string,v:string,scope:ParentNode=document){if(!v)return;const el=alanInput(baslik,scope);if(!el)return;el.focus();nativeDeger(el,v);el.blur();await bekle(60);}
async function comboDoldur(baslik:string,v:string,scope:ParentNode=document){if(!v)return;const el=alanInput(baslik,scope) as HTMLInputElement|null;if(!el)return;el.focus();await bekle(50);nativeDeger(el,v);await bekle(120);const hedef=norm(v);const sec=Array.from(document.querySelectorAll<HTMLButtonElement>("button")).find(x=>{const t=norm(x.textContent||"");return t===hedef||t.startsWith(`${hedef} `);});if(sec){sec.click();await bekle(100);return;}el.dispatchEvent(new KeyboardEvent("keydown",{key:"Enter",code:"Enter",bubbles:true,cancelable:true}));await bekle(100);}
function bolumBul(baslik:string){const h=Array.from(document.querySelectorAll<HTMLElement>("h2")).find(x=>norm(x.textContent||"")===norm(baslik));return h?.closest("div.rounded-2xl")||h?.parentElement?.parentElement?.parentElement||document;}

export default function HaritaGelismisIslemler(){
 useEffect(()=>{
  let uyduSecildi=false,fsHandler:(()=>void)|null=null,ekleTimer:number|undefined,uyduTimer:number|undefined;
  let konumMarker:any=null,konumDaire:any=null;
  const uyduyuAc=()=>{if(uyduSecildi)return true;const uydu=Array.from(document.querySelectorAll<HTMLButtonElement>("button")).find(x=>norm(x.textContent||"").includes("uydu gorunumu"));if(uydu){uyduSecildi=true;uydu.click();return true;}return false;};
  const ekle=()=>{
   const harita=document.querySelector<HTMLElement>(".leaflet-container");if(!harita)return;
   if(!uyduSecildi)window.setTimeout(uyduyuAc,120);
   if(!harita.querySelector('[data-harita-full="1"]')){harita.style.position="relative";const b=document.createElement("button");b.type="button";b.dataset.haritaFull="1";b.textContent="⛶ Tam Ekran";b.style.cssText="position:absolute;right:12px;top:12px;z-index:10000;background:#0f172a;color:#fff;border:2px solid #fff;border-radius:10px;padding:8px 11px;font-size:11px;font-weight:900;box-shadow:0 4px 14px rgba(15,23,42,.35);cursor:pointer";const duzenle=()=>{const tam=document.fullscreenElement===harita;b.textContent=tam?"✕ Tam Ekrandan Çık":"⛶ Tam Ekran";if(tam){harita.style.width="100vw";harita.style.height="100vh";harita.style.minHeight="100vh";harita.style.maxHeight="100vh";harita.style.margin="0";harita.style.borderRadius="0";harita.style.overflow="hidden";document.documentElement.style.overflow="hidden";document.body.style.overflow="hidden";}else{harita.style.width="";harita.style.height="";harita.style.minHeight="";harita.style.maxHeight="";harita.style.margin="";harita.style.borderRadius="";harita.style.overflow="";document.documentElement.style.overflow="";document.body.style.overflow="";}window.setTimeout(()=>window.dispatchEvent(new Event("resize")),150);};b.onclick=async()=>{try{if(document.fullscreenElement===harita)await document.exitFullscreen();else await harita.requestFullscreen();}catch{}};fsHandler=duzenle;document.addEventListener("fullscreenchange",duzenle);harita.appendChild(b);}
   if(!harita.querySelector('[data-harita-konum="1"]')){const b=document.createElement("button");b.type="button";b.dataset.haritaKonum="1";b.textContent="📍 Konumum";b.style.cssText="position:absolute;right:12px;top:54px;z-index:10000;background:#fff;color:#0f172a;border:2px solid #cbd5e1;border-radius:10px;padding:8px 11px;font-size:11px;font-weight:900;box-shadow:0 4px 14px rgba(15,23,42,.18);cursor:pointer";b.onclick=()=>{if(!navigator.geolocation){b.textContent="Konum desteklenmiyor";return;}b.textContent="📍 Konum alınıyor...";navigator.geolocation.getCurrentPosition(pos=>{const map=(harita as any)._leaflet_map||Object.values((window as any).L?._instances||{}).find((x:any)=>x?.setView);const L=(window as any).L;if(!map||!L){b.textContent="📍 Konumum";return;}const lat=pos.coords.latitude,lng=pos.coords.longitude;if(konumMarker)map.removeLayer(konumMarker);if(konumDaire)map.removeLayer(konumDaire);konumDaire=L.circle([lat,lng],{radius:Math.max(pos.coords.accuracy,20),color:"#2563eb",weight:1,fillOpacity:.10}).addTo(map);konumMarker=L.circleMarker([lat,lng],{radius:8,color:"#fff",weight:3,fillColor:"#2563eb",fillOpacity:1}).addTo(map).bindPopup(`<b>📍 Konumum</b><br><span style="font-size:11px">Doğruluk: yaklaşık ${Math.round(pos.coords.accuracy)} m</span>`);map.setView([lat,lng],17);konumMarker.openPopup();b.textContent="📍 Konumum";},()=>{b.textContent="⚠ Konum alınamadı";window.setTimeout(()=>b.textContent="📍 Konumum",2200);},{enableHighAccuracy:true,timeout:10000,maximumAge:30000});};harita.appendChild(b);}
   document.querySelectorAll<HTMLElement>(".leaflet-popup-content").forEach(p=>{const txt=p.innerText||"",lok=alan(txt,"Lokasyon ID");if(!lok)return;if(!p.querySelector('[data-harita-yol="1"]')){const b=document.createElement("button");b.type="button";b.dataset.haritaYol="1";b.textContent="🧭 Yol Tarifi";b.style.cssText="width:100%;margin-top:8px;padding:9px 12px;border:0;border-radius:10px;background:#16a34a;color:#fff;font-size:12px;font-weight:800;cursor:pointer";b.onclick=()=>{const q=[alan(txt,"TR / Trafo Bölge Adı"),alan(txt,"Mahalle"),alan(txt,"İlçe")].filter(Boolean).join(" ")||lok;window.open(`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(q)}`,"_blank","noopener,noreferrer");};p.appendChild(b);}if(!p.querySelector('[data-harita-yeni="1"]')){const baslik=(txt.split("\n")[0]||"").replace(/^⚡\s*/,"").trim();const detay={lokasyonId:lok,trafoId:alan(txt,"Trafo ID"),ilce:alan(txt,"İlçe"),mahalle:alan(txt,"Mahalle"),tr:baslik,trafoTipi:/bina/i.test(alan(txt,"Montaj Tipi"))?"BİNA":/direk/i.test(alan(txt,"Montaj Tipi"))?"DİREK":""};const b=document.createElement("button");b.type="button";b.dataset.haritaYeni="1";b.textContent="➕ Değişim Kaydı Oluştur";b.style.cssText="width:100%;margin-top:8px;padding:9px 12px;border:0;border-radius:10px;background:#2563eb;color:#fff;font-size:12px;font-weight:800;cursor:pointer";b.onclick=()=>window.dispatchEvent(new CustomEvent("trafo-harita-yeni-kayit",{detail:detay}));p.appendChild(b);}});
  };
  const yeni=async(e:Event)=>{const d=(e as CustomEvent).detail||{};if(!d.lokasyonId)return;const nav=Array.from(document.querySelectorAll<HTMLButtonElement>("nav button"));const b=nav.find(x=>norm(x.textContent||"").includes("yeni kayit"));if(!b)return;b.click();for(let i=0;i<30&&!Array.from(document.querySelectorAll("h1")).some(x=>norm(x.textContent||"").includes("yeni trafo degisim kaydi"));i++)await bekle(100);const konum=bolumBul("Konum Bilgileri");await comboDoldur("İlçe",d.ilce||"",konum);await comboDoldur("Mahalle",d.mahalle||"",konum);await metinDoldur("TR / Trafo Bölge Adı",d.tr||"",konum);await metinDoldur("Lokasyon ID",String(d.lokasyonId||""),konum);await metinDoldur("Trafo ID",String(d.trafoId||""),konum);await comboDoldur("Trafo Tipi",d.trafoTipi||"",konum);window.scrollTo({top:0,behavior:"smooth"});};
  window.addEventListener("trafo-harita-yeni-kayit",yeni);
  const o=new MutationObserver(()=>{if(ekleTimer)window.clearTimeout(ekleTimer);ekleTimer=window.setTimeout(ekle,180);});o.observe(document.body,{childList:true,subtree:true});ekle();
  let deneme=0;uyduTimer=window.setInterval(()=>{deneme++;if(uyduyuAc()||deneme>20){if(uyduTimer)window.clearInterval(uyduTimer);}},300);
  return()=>{o.disconnect();if(ekleTimer)window.clearTimeout(ekleTimer);if(uyduTimer)window.clearInterval(uyduTimer);window.removeEventListener("trafo-harita-yeni-kayit",yeni);if(fsHandler)document.removeEventListener("fullscreenchange",fsHandler);document.documentElement.style.overflow="";document.body.style.overflow="";};
 },[]);return null;
}
