"use client";

import { ChangeEvent, useEffect, useMemo, useRef, useState } from "react";

declare global { interface Window { L?: any; shp?: (data:ArrayBuffer)=>Promise<any>; } }

type GeoFeature={type:string;geometry:any;properties:Record<string,any>};
type GeoJSON={type:"FeatureCollection";features:GeoFeature[]};
type Secili={tur:"nokta"|"bina";feature:GeoFeature}|null;
type Yakin={feature:GeoFeature;mesafe:number};

const ILCE_LISTESI=["Altıeylül","Karesi","Balya","Bigadiç","Dursunbey","İvrindi","Kepsut","Savaştepe","Sındırgı","Susurluk"];
const DB="trafo-harita-db",STORE="dosyalar",KEY="shp-zip";
const norm=(v:any)=>String(v??"").trim();
const prop=(p:any,...keys:string[])=>{for(const k of keys){if(p?.[k]!=null&&String(p[k]).trim()!=="")return p[k];}return "";};
const num=(v:any)=>{const n=Number(String(v??"").replace(",","."));return Number.isFinite(n)?n:null;};

function dbAc(){return new Promise<IDBDatabase>((ok,no)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE)};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error);});}
async function kaydetBlob(blob:Blob){const db=await dbAc();await new Promise<void>((ok,no)=>{const tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).put(blob,KEY);tx.oncomplete=()=>ok();tx.onerror=()=>no(tx.error);});db.close();}
async function okuBlob(){const db=await dbAc();const v=await new Promise<any>((ok,no)=>{const tx=db.transaction(STORE,"readonly");const r=tx.objectStore(STORE).get(KEY);r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error);});db.close();return v as Blob|undefined;}
async function silBlob(){const db=await dbAc();await new Promise<void>((ok,no)=>{const tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).delete(KEY);tx.oncomplete=()=>ok();tx.onerror=()=>no(tx.error);});db.close();}
function scriptYukle(id:string,src:string,test:()=>boolean){return new Promise<void>((ok,no)=>{if(test())return ok();const eski=document.getElementById(id) as HTMLScriptElement|null;if(eski){eski.addEventListener("load",()=>ok(),{once:true});eski.addEventListener("error",()=>no(new Error("Kütüphane yüklenemedi")),{once:true});return;}const s=document.createElement("script");s.id=id;s.src=src;s.onload=()=>ok();s.onerror=()=>no(new Error("Kütüphane yüklenemedi"));document.body.appendChild(s);});}
function koleksiyonlar(x:any):GeoJSON[]{if(!x)return[];if(Array.isArray(x))return x.flatMap(koleksiyonlar);if(x.type==="FeatureCollection"&&Array.isArray(x.features))return[x];return[];}
function ayir(x:any){const cols=koleksiyonlar(x),nokta:GeoFeature[]=[],bina:GeoFeature[]=[];for(const c of cols)for(const f of c.features||[]){const t=f?.geometry?.type||"";if(t==="Point"||t==="MultiPoint")nokta.push(f);else if(t.includes("Polygon"))bina.push(f);}return{nokta:{type:"FeatureCollection",features:nokta} as GeoJSON,bina:{type:"FeatureCollection",features:bina} as GeoJSON};}
function mesafeKm(aLat:number,aLng:number,bLat:number,bLng:number){const R=6371,toRad=(x:number)=>x*Math.PI/180,dLat=toRad(bLat-aLat),dLng=toRad(bLng-aLng);const q=Math.sin(dLat/2)**2+Math.cos(toRad(aLat))*Math.cos(toRad(bLat))*Math.sin(dLng/2)**2;return 2*R*Math.asin(Math.sqrt(q));}
function koordinat(f:GeoFeature){if(f.geometry?.type==="Point"&&Array.isArray(f.geometry.coordinates)){const [lng,lat]=f.geometry.coordinates;return {lat:Number(lat),lng:Number(lng)};}return null;}

export default function TrafoHarita(){
 const mapEl=useRef<HTMLDivElement|null>(null),mapRef=useRef<any>(null),pointLayer=useRef<any>(null),buildingLayer=useRef<any>(null),konumLayer=useRef<any>(null),tileLayer=useRef<any>(null),pointData=useRef<GeoJSON|null>(null),buildingData=useRef<GeoJSON|null>(null);
 const [hazir,setHazir]=useState(false),[veriHazir,setVeriHazir]=useState(false),[hata,setHata]=useState(""),[durum,setDurum]=useState(""),[dosyaAdi,setDosyaAdi]=useState("");
 const [ilce,setIlce]=useState(""),[arama,setArama]=useState(""),[noktaAcik,setNoktaAcik]=useState(true),[binaAcik,setBinaAcik]=useState(true),[noktaSayisi,setNoktaSayisi]=useState(0),[binaSayisi,setBinaSayisi]=useState(0);
 const [secili,setSecili]=useState<Secili>(null),[konum,setKonum]=useState<{lat:number;lng:number}|null>(null),[yakinlar,setYakinlar]=useState<Yakin[]>([]),[konumYukleniyor,setKonumYukleniyor]=useState(false),[haritaTipi,setHaritaTipi]=useState<"standart"|"uydu">("standart");

 const veriyiKur=(x:any,ad:string)=>{const a=ayir(x);pointData.current=a.nokta;buildingData.current=a.bina;setDosyaAdi(ad);setVeriHazir(true);setDurum(`${a.nokta.features.length.toLocaleString("tr-TR")} trafo noktası • ${a.bina.features.length.toLocaleString("tr-TR")} trafo binası`);setHata("");};
 const zipOku=async(blob:Blob,ad:string)=>{if(!window.shp)throw new Error("SHP okuyucu hazır değil");setDurum("SHP ZIP okunuyor...");const x=await window.shp(await blob.arrayBuffer());veriyiKur(x,ad);};

 useEffect(()=>{let kapandi=false;const baslat=async()=>{try{if(!document.getElementById("leaflet-css-trafo")){const l=document.createElement("link");l.id="leaflet-css-trafo";l.rel="stylesheet";l.href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css";document.head.appendChild(l);}await Promise.all([scriptYukle("leaflet-js-trafo","https://unpkg.com/leaflet@1.9.4/dist/leaflet.js",()=>!!window.L),scriptYukle("shpjs-trafo","https://unpkg.com/shpjs@6.1.0/dist/shp.js",()=>!!window.shp)]);if(kapandi||!mapEl.current)return;const L=window.L;const map=L.map(mapEl.current,{zoomControl:true,preferCanvas:true}).setView([39.65,27.9],9);tileLayer.current=L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:20,attribution:'&copy; OpenStreetMap'}).addTo(map);mapRef.current=map;setHazir(true);const eski=await okuBlob();if(eski&&!kapandi){try{await zipOku(eski,"Kayıtlı SHP envanteri");}catch{setDurum("Kayıtlı SHP okunamadı. ZIP'i yeniden yükleyin.");}}}catch(e:any){if(!kapandi)setHata(e?.message||"Harita yüklenemedi");}};baslat();return()=>{kapandi=true;if(mapRef.current){mapRef.current.remove();mapRef.current=null;}};},[]);

 useEffect(()=>{if(!hazir||!mapRef.current||!window.L)return;const L=window.L,map=mapRef.current;if(tileLayer.current)map.removeLayer(tileLayer.current);tileLayer.current=haritaTipi==="uydu"?L.tileLayer("https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",{maxZoom:19,attribution:"Esri"}):L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:20,attribution:'&copy; OpenStreetMap'});tileLayer.current.addTo(map);tileLayer.current.bringToBack?.();},[haritaTipi,hazir]);

 useEffect(()=>{if(!hazir||!veriHazir||!mapRef.current||!window.L||!pointData.current||!buildingData.current)return;const L=window.L,map=mapRef.current;if(pointLayer.current){map.removeLayer(pointLayer.current);pointLayer.current=null;}if(buildingLayer.current){map.removeLayer(buildingLayer.current);buildingLayer.current=null;}const q=arama.trim().toLocaleLowerCase("tr-TR");const uygun=(f:GeoFeature)=>{const p=f.properties||{};const fi=norm(prop(p,"ILCE","ilce"));if(ilce&&fi.toLocaleLowerCase("tr-TR")!==ilce.toLocaleLowerCase("tr-TR"))return false;if(!q)return true;return ["ADI","ID","GIS_ID","LOKASYON_I","KODU","MAHALLE","MARKA","SERI_NO","SERI_NUMAR","GUC"].some(k=>norm(p[k]).toLocaleLowerCase("tr-TR").includes(q));};const pts={type:"FeatureCollection",features:pointData.current.features.filter(uygun)} as GeoJSON;const bins={type:"FeatureCollection",features:buildingData.current.features.filter(uygun)} as GeoJSON;setNoktaSayisi(pts.features.length);setBinaSayisi(bins.features.length);
 if(binaAcik)buildingLayer.current=L.geoJSON(bins,{style:()=>({color:"#6d28d9",weight:1.5,fillColor:"#8b5cf6",fillOpacity:.16}),onEachFeature:(f:any,l:any)=>l.on("click",()=>setSecili({tur:"bina",feature:f}))}).addTo(map);
 if(noktaAcik)pointLayer.current=L.geoJSON(pts,{pointToLayer:(_f:any,ll:any)=>L.circleMarker(ll,{radius:5,color:"#c2410c",weight:1.4,fillColor:"#f97316",fillOpacity:.88}),onEachFeature:(f:any,l:any)=>l.on("click",()=>setSecili({tur:"nokta",feature:f}))}).addTo(map);
 const layers=[pointLayer.current,buildingLayer.current].filter(Boolean);if(layers.length){const bounds=L.featureGroup(layers).getBounds();if(bounds.isValid()&&(ilce||q))map.fitBounds(bounds.pad(.08),{maxZoom:q?17:12});else if(bounds.isValid()&&!ilce&&!q)map.fitBounds(bounds.pad(.04),{maxZoom:11});}},[hazir,veriHazir,ilce,arama,noktaAcik,binaAcik]);

 const yukle=async(e:ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];e.target.value="";if(!f)return;if(!f.name.toLowerCase().endsWith(".zip")){setHata("SHP dosyalarını içeren ZIP seçmelisiniz.");return;}try{await zipOku(f,f.name);await kaydetBlob(f);setDurum(d=>`${d} • bu cihazda kaydedildi`);}catch(err:any){setHata(err?.message||"SHP ZIP okunamadı");}};
 const temizle=async()=>{await silBlob();pointData.current=null;buildingData.current=null;setVeriHazir(false);setDosyaAdi("");setDurum("Kayıtlı SHP verisi silindi.");setNoktaSayisi(0);setBinaSayisi(0);setSecili(null);setYakinlar([]);if(pointLayer.current&&mapRef.current)mapRef.current.removeLayer(pointLayer.current);if(buildingLayer.current&&mapRef.current)mapRef.current.removeLayer(buildingLayer.current);pointLayer.current=null;buildingLayer.current=null;};
 const tumunuGoster=()=>{setIlce("");setArama("");setSecili(null);setYakinlar([]);mapRef.current?.setView([39.65,27.9],9);};
 const konumumaGit=()=>{if(!navigator.geolocation){setHata("Bu cihaz konum özelliğini desteklemiyor.");return;}setKonumYukleniyor(true);setHata("");navigator.geolocation.getCurrentPosition(pos=>{const k={lat:pos.coords.latitude,lng:pos.coords.longitude};setKonum(k);setKonumYukleniyor(false);const L=window.L,map=mapRef.current;if(L&&map){if(konumLayer.current)map.removeLayer(konumLayer.current);konumLayer.current=L.circleMarker([k.lat,k.lng],{radius:8,color:"#1d4ed8",weight:3,fillColor:"#60a5fa",fillOpacity:.9}).addTo(map).bindTooltip("Konumunuz",{permanent:false});map.setView([k.lat,k.lng],14);}if(pointData.current){const list=pointData.current.features.map(f=>{const c=koordinat(f);return c?{feature:f,mesafe:mesafeKm(k.lat,k.lng,c.lat,c.lng)}:null;}).filter(Boolean) as Yakin[];list.sort((a,b)=>a.mesafe-b.mesafe);setYakinlar(list.slice(0,10));}},()=>{setKonumYukleniyor(false);setHata("Konum alınamadı. Tarayıcı konum iznini kontrol edin.");},{enableHighAccuracy:true,timeout:10000});};
 const yakinSec=(y:Yakin)=>{const c=koordinat(y.feature);if(!c)return;setSecili({tur:"nokta",feature:y.feature});mapRef.current?.setView([c.lat,c.lng],18);};
 const toplam=useMemo(()=>noktaSayisi+binaSayisi,[noktaSayisi,binaSayisi]);
 const p=secili?.feature.properties||{};

 return <div className="space-y-4">
  <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
   <Kart ikon="⚡" baslik="TRAFO NOKTALARI" deger={veriHazir?String(noktaSayisi):"—"} alt="Filtrelenen nokta"/>
   <Kart ikon="🏢" baslik="TRAFO BİNALARI" deger={veriHazir?String(binaSayisi):"—"} alt="Filtrelenen bina"/>
   <Kart ikon="📍" baslik="İLÇE" deger={ilce||"Tümü"} alt="Aktif harita filtresi"/>
   <Kart ikon="🧭" baslik="YAKIN TRAFOLAR" deger={yakinlar.length?String(yakinlar.length):"—"} alt={konum?"Konumunuza göre":"Konum kullanılmadı"}/>
  </div>

  <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-[0_10px_30px_rgba(15,23,42,.07)]">
   <div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><div className="text-sm font-black text-slate-800">🗺️ Trafo Envanteri</div><div className="mt-1 text-xs text-slate-500">{dosyaAdi||"Henüz SHP ZIP yüklenmedi"}{durum&&` • ${durum}`}</div></div><div className="flex flex-wrap gap-2"><button type="button" onClick={konumumaGit} disabled={konumYukleniyor} className="rounded-xl border border-blue-200 bg-blue-50 px-4 py-2.5 text-xs font-black text-blue-700 disabled:opacity-50">📍 {konumYukleniyor?"Konum alınıyor...":"Konumuma Git"}</button><label className="cursor-pointer rounded-xl bg-blue-600 px-4 py-2.5 text-xs font-black text-white shadow-sm hover:bg-blue-700">📂 {veriHazir?"SHP Güncelle":"SHP ZIP Yükle"}<input type="file" accept=".zip,application/zip" onChange={yukle} className="hidden"/></label>{veriHazir&&<button type="button" onClick={temizle} className="rounded-xl border border-red-200 bg-white px-4 py-2.5 text-xs font-black text-red-600">Veriyi Sil</button>}</div></div>
   {veriHazir&&<><div className="my-4 border-t border-slate-100"/><div className="grid gap-3 lg:grid-cols-[220px_minmax(0,1fr)_auto]"><select value={ilce} onChange={e=>setIlce(e.target.value)} className="rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm"><option value="">Tüm İlçeler</option>{ILCE_LISTESI.map(x=><option key={x}>{x}</option>)}</select><input value={arama} onChange={e=>setArama(e.target.value)} placeholder="Trafo adı, ID, GIS ID, mahalle, marka, seri no, güç ara..." className="rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm"/><button type="button" onClick={tumunuGoster} className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-xs font-black text-slate-600">Filtreyi Temizle</button></div><div className="mt-3 flex flex-wrap items-center gap-2 border-t border-slate-100 pt-3"><button onClick={()=>setNoktaAcik(v=>!v)} className={`rounded-xl border px-3 py-2 text-xs font-black ${noktaAcik?"border-orange-200 bg-orange-50 text-orange-700":"border-slate-200 bg-white text-slate-500"}`}>⚡ Trafo Noktaları ({noktaSayisi})</button><button onClick={()=>setBinaAcik(v=>!v)} className={`rounded-xl border px-3 py-2 text-xs font-black ${binaAcik?"border-violet-200 bg-violet-50 text-violet-700":"border-slate-200 bg-white text-slate-500"}`}>🏢 Trafo Binaları ({binaSayisi})</button><button onClick={()=>setHaritaTipi(x=>x==="standart"?"uydu":"standart")} className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs font-black text-slate-600">{haritaTipi==="standart"?"🛰️ Uydu Görünümü":"🗺️ Standart Harita"}</button><span className="ml-auto text-[11px] font-bold text-slate-400">Görünen toplam: {toplam}</span></div></>}
  </div>

  {hata&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-bold text-red-700">{hata}</div>}

  <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_350px]">
   <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-[0_10px_30px_rgba(15,23,42,.08)]"><div className="flex items-center justify-between border-b border-slate-200 px-4 py-3"><div><div className="text-sm font-black text-slate-800">Balıkesir Trafo Envanter Haritası</div><div className="mt-0.5 text-[10px] text-slate-400">Noktaya veya bina alanına tıklayarak detayları açın</div></div><span className={`rounded-full px-2.5 py-1 text-[9px] font-black ${hazir?"bg-emerald-100 text-emerald-700":"bg-amber-100 text-amber-700"}`}>{hazir?"HARİTA HAZIR":"YÜKLENİYOR"}</span></div><div ref={mapEl} className="h-[68vh] min-h-[540px] w-full"/></div>

   <div className="space-y-4">
    <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><div className="text-sm font-black text-slate-800">{secili?secili.tur==="nokta"?"⚡ Trafo Detayı":"🏢 Bina Detayı":"Detay Paneli"}</div>{secili&&<button onClick={()=>setSecili(null)} className="rounded-lg border border-slate-200 px-2.5 py-1.5 text-xs">×</button>}</div>{secili?<div className="mt-4 space-y-2"><Detay b="Adı" v={prop(p,"ADI")}/><Detay b="İlçe" v={prop(p,"ILCE")}/><Detay b="Mahalle" v={prop(p,"MAHALLE")}/>{secili.tur==="nokta"?<><Detay b="Trafo ID" v={prop(p,"ID")}/><Detay b="GIS ID" v={prop(p,"GIS_ID")}/><Detay b="Lokasyon ID" v={prop(p,"LOKASYON_I")}/><Detay b="Güç" v={prop(p,"GUC")?`${prop(p,"GUC")} kVA`:""}/><Detay b="Primer Gerilim" v={prop(p,"PRIMER_GER")}/><Detay b="Marka" v={prop(p,"MARKA")}/><Detay b="Seri No" v={prop(p,"SERI_NO")}/><Detay b="İmal Yılı" v={prop(p,"IMAL_YILI")}/><Detay b="Tip" v={prop(p,"TIPI")}/><Detay b="Cinsi" v={prop(p,"CINSI")}/></>:<><Detay b="Bina ID" v={prop(p,"ID")}/><Detay b="Kodu" v={prop(p,"KODU")}/><Detay b="Tip" v={prop(p,"TIPI")}/><Detay b="Alt Tip" v={prop(p,"ALTTIP")}/><Detay b="Gerilim" v={prop(p,"ISLETME_GE")}/></>}</div>:<div className="mt-4 rounded-xl border border-dashed border-slate-300 bg-slate-50 p-6 text-center text-xs leading-5 text-slate-500">Haritadaki bir trafo noktasına veya bina alanına tıklayın. Tüm bilgiler burada düzenli şekilde görünecek.</div>}</div>

    <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><div><div className="text-sm font-black text-slate-800">📍 Yakınımdaki Trafolar</div><div className="mt-1 text-[10px] text-slate-400">Konumunuza en yakın 10 trafo</div></div><button onClick={konumumaGit} className="rounded-lg border border-blue-200 bg-blue-50 px-2.5 py-1.5 text-[10px] font-black text-blue-700">Yenile</button></div><div className="mt-3 space-y-2">{yakinlar.length?yakinlar.map((y,i)=>{const pp=y.feature.properties||{};return <button key={`${prop(pp,"ID")}-${i}`} onClick={()=>yakinSec(y)} className="flex w-full items-center justify-between gap-3 rounded-xl border border-slate-200 bg-slate-50 px-3 py-3 text-left hover:border-blue-300 hover:bg-blue-50"><div className="min-w-0"><div className="truncate text-xs font-black text-slate-800">{prop(pp,"ADI")||`Trafo ${prop(pp,"ID")}`}</div><div className="mt-1 truncate text-[10px] text-slate-400">{prop(pp,"ILCE")} • {prop(pp,"MAHALLE")}</div></div><span className="shrink-0 rounded-full bg-blue-100 px-2 py-1 text-[10px] font-black text-blue-700">{y.mesafe<1?`${Math.round(y.mesafe*1000)} m`:`${y.mesafe.toFixed(1)} km`}</span></button>}):<div className="rounded-xl border border-dashed border-slate-300 bg-slate-50 p-5 text-center text-xs text-slate-500">“Konumuma Git” ile en yakın trafolar listelenir.</div>}</div></div>
   </div>
  </div>
 </div>;
}

function Kart({ikon,baslik,deger,alt}:{ikon:string;baslik:string;deger:string;alt:string}){return <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-blue-50 text-xl">{ikon}</div><div className="min-w-0"><div className="text-[9px] font-black uppercase tracking-wider text-slate-400">{baslik}</div><div className="mt-1 truncate text-xl font-black text-slate-900">{deger}</div><div className="mt-0.5 truncate text-[10px] text-slate-400">{alt}</div></div></div></div>}
function Detay({b,v}:{b:string;v:any}){return <div className="flex items-start justify-between gap-3 rounded-xl border border-slate-100 bg-slate-50 px-3 py-2.5"><span className="text-[10px] font-bold text-slate-400">{b}</span><span className="max-w-[62%] break-words text-right text-xs font-black text-slate-700">{norm(v)||"—"}</span></div>}
