"use client";

import { ChangeEvent, useEffect, useMemo, useRef, useState } from "react";
import { createClient } from "@supabase/supabase-js";

declare global { interface Window { L?: any; shp?: (data:ArrayBuffer)=>Promise<any>; } }
type GeoFeature={type:string;geometry:any;properties:Record<string,any>};
type GeoJSON={type:"FeatureCollection";features:GeoFeature[]};
type DegisimKaydi={id:number;trafo_id:string|null;lokasyon_id:string|null;tr:string|null;tarih:string|null};
type XY=[number,number];
const ILCE_LISTESI=["Altıeylül","Karesi","Balya","Bigadiç","Dursunbey","İvrindi","Kepsut","Savaştepe","Sındırgı","Susurluk"];
const DB="trafo-harita-db",STORE="dosyalar",KEY="shp-zip";
const norm=(v:any)=>String(v??"").trim();
const anahtar=(v:any)=>String(v??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/ı/g,"I").replace(/İ/g,"I").toUpperCase().replace(/[^A-Z0-9]+/g," ").trim().replace(/\s+/g," ");
const esc=(v:any)=>String(v??"—").replace(/[&<>'\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'\"':"&quot;"}[c]||c));
const prop=(p:any,...keys:string[])=>{for(const k of keys)if(p?.[k]!=null&&String(p[k]).trim()!=="")return p[k];return "";};
function dbAc(){return new Promise<IDBDatabase>((ok,no)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE)};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error);});}
async function kaydetBlob(blob:Blob){const db=await dbAc();await new Promise<void>((ok,no)=>{const tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).put(blob,KEY);tx.oncomplete=()=>ok();tx.onerror=()=>no(tx.error);});db.close();}
async function okuBlob(){const db=await dbAc();const v=await new Promise<any>((ok,no)=>{const tx=db.transaction(STORE,"readonly");const r=tx.objectStore(STORE).get(KEY);r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error);});db.close();return v as Blob|undefined;}
function scriptYukle(id:string,src:string,test:()=>boolean){return new Promise<void>((ok,no)=>{if(test())return ok();const eski=document.getElementById(id) as HTMLScriptElement|null;if(eski){eski.addEventListener("load",()=>ok(),{once:true});eski.addEventListener("error",()=>no(new Error("Kütüphane yüklenemedi")),{once:true});return;}const s=document.createElement("script");s.id=id;s.src=src;s.onload=()=>ok();s.onerror=()=>no(new Error("Kütüphane yüklenemedi"));document.body.appendChild(s);});}
function koleksiyonlar(x:any):GeoJSON[]{if(!x)return[];if(Array.isArray(x))return x.flatMap(koleksiyonlar);if(x.type==="FeatureCollection"&&Array.isArray(x.features))return[x];return[];}
function ayir(x:any){const cols=koleksiyonlar(x),nokta:GeoFeature[]=[],bina:GeoFeature[]=[];for(const c of cols)for(const f of c.features||[]){const t=f?.geometry?.type||"";if(t==="Point"||t==="MultiPoint")nokta.push(f);else if(t.includes("Polygon"))bina.push(f);}return{nokta:{type:"FeatureCollection",features:nokta} as GeoJSON,bina:{type:"FeatureCollection",features:bina} as GeoJSON};}
function halkadaMi(pt:XY,ring:any[]){let ic=false;const [x,y]=pt;for(let i=0,j=ring.length-1;i<ring.length;j=i++){const xi=ring[i]?.[0],yi=ring[i]?.[1],xj=ring[j]?.[0],yj=ring[j]?.[1];if(((yi>y)!==(yj>y))&&(x<(xj-xi)*(y-yi)/((yj-yi)||1e-15)+xi))ic=!ic;}return ic;}
function poligondaMi(pt:XY,rings:any[]){if(!rings?.length||!halkadaMi(pt,rings[0]))return false;for(let i=1;i<rings.length;i++)if(halkadaMi(pt,rings[i]))return false;return true;}
function geometrideMi(pt:XY,g:any){if(g?.type==="Polygon")return poligondaMi(pt,g.coordinates);if(g?.type==="MultiPolygon")return (g.coordinates||[]).some((p:any)=>poligondaMi(pt,p));return false;}
function bbox(g:any):[number,number,number,number]|null{let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;const gez=(x:any)=>{if(Array.isArray(x)&&x.length>=2&&typeof x[0]==="number"&&typeof x[1]==="number"){minX=Math.min(minX,x[0]);minY=Math.min(minY,x[1]);maxX=Math.max(maxX,x[0]);maxY=Math.max(maxY,x[1]);}else if(Array.isArray(x))x.forEach(gez);};gez(g?.coordinates);return Number.isFinite(minX)?[minX,minY,maxX,maxY]:null;}
function trafoNoktalari(fs:GeoFeature[]){const out:XY[]=[];for(const f of fs){const g=f.geometry;if(g?.type==="Point")out.push(g.coordinates as XY);else if(g?.type==="MultiPoint")for(const p of g.coordinates||[])out.push(p as XY);}return out;}
function trafosuzBinalar(noktalar:GeoFeature[],binalar:GeoFeature[]){const pts=trafoNoktalari(noktalar),hucre=.01,grid=new Map<string,XY[]>();for(const p of pts){const k=`${Math.floor(p[0]/hucre)}:${Math.floor(p[1]/hucre)}`,a=grid.get(k)||[];a.push(p);grid.set(k,a);}return binalar.filter(f=>{const b=bbox(f.geometry);if(!b)return true;const [minX,minY,maxX,maxY]=b;for(let gx=Math.floor(minX/hucre);gx<=Math.floor(maxX/hucre);gx++)for(let gy=Math.floor(minY/hucre);gy<=Math.floor(maxY/hucre);gy++)for(const p of grid.get(`${gx}:${gy}`)||[])if(p[0]>=minX&&p[0]<=maxX&&p[1]>=minY&&p[1]<=maxY&&geometrideMi(p,f.geometry))return false;return true;});}
function tarihGoster(t:string|null){if(!t)return"—";const p=t.split("-");return p.length===3?`${p[2]}.${p[1]}.${p[0]}`:t;}
function noktaPopup(p:any,adet:number,sonTarih:string|null){return `<div style="min-width:245px;font-family:Arial"><b>⚡ ${esc(prop(p,"ADI")||"Trafo")}</b><div>İlçe: ${esc(prop(p,"ILCE"))}</div><div>Mahalle: ${esc(prop(p,"MAHALLE"))}</div><div>Trafo ID: ${esc(prop(p,"ID"))}</div><div>Lokasyon ID: ${esc(prop(p,"LOKASYON_I"))}</div><div>Güç: ${esc(prop(p,"GUC"))}</div><div style="margin-top:8px;font-weight:800">${adet?`🕘 ${adet} değişim kaydı${sonTarih?` • ${esc(tarihGoster(sonTarih))}`:""}`:"Değişim kaydı yok"}</div></div>`;}
function kokPopup(p:any){return `<div style="min-width:235px;font-family:Arial"><b>🏢 ${esc(prop(p,"ADI")||"Trafosuz KÖK")}</b><div style="margin:6px 0;font-weight:900;color:#0369a1">TRAFOSUZ KÖK BİNASI</div><div>İlçe: ${esc(prop(p,"ILCE"))}</div><div>Mahalle: ${esc(prop(p,"MAHALLE"))}</div><div>Bina ID: ${esc(prop(p,"ID"))}</div><div>Kodu: ${esc(prop(p,"KODU"))}</div><div>Alt Tip: ${esc(prop(p,"ALTTIP"))}</div></div>`;}
export default function TrafoHarita(){
 const mapEl=useRef<HTMLDivElement|null>(null),mapRef=useRef<any>(null),pointLayer=useRef<any>(null),buildingLayer=useRef<any>(null),tileLayer=useRef<any>(null),pointData=useRef<GeoJSON|null>(null),kokData=useRef<GeoJSON|null>(null);
 const [hazir,setHazir]=useState(false),[veriHazir,setVeriHazir]=useState(false),[hata,setHata]=useState(""),[durum,setDurum]=useState("Merkezi envanter kontrol ediliyor..."),[dosyaAdi,setDosyaAdi]=useState("");
 const [ilce,setIlce]=useState(""),[arama,setArama]=useState(""),[noktaAcik,setNoktaAcik]=useState(true),[binaAcik,setBinaAcik]=useState(true),[noktaSayisi,setNoktaSayisi]=useState(0),[binaSayisi,setBinaSayisi]=useState(0),[haritaTipi,setHaritaTipi]=useState<"standart"|"uydu">("standart");
 const [degisimKayitlari,setDegisimKayitlari]=useState<DegisimKaydi[]>([]),[degisimYukleniyor,setDegisimYukleniyor]=useState(true),[sadeceDegisen,setSadeceDegisen]=useState(false),[eslesenSayisi,setEslesenSayisi]=useState(0),[tekDegisimSayisi,setTekDegisimSayisi]=useState(0),[cokDegisimSayisi,setCokDegisimSayisi]=useState(0);
 const [merkezi,setMerkezi]=useState(false),[adminMi,setAdminMi]=useState(false),[envanterIslem,setEnvanterIslem]=useState(false);
 const supabase=useMemo(()=>{const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;return url&&key?createClient(url,key):null;},[]);
 const degisimIndex=useMemo(()=>{const idx=new Map<string,Set<number>>(),byId=new Map<number,DegisimKaydi>();for(const k of degisimKayitlari){byId.set(k.id,k);const a=anahtar(k.lokasyon_id);if(a){if(!idx.has(a))idx.set(a,new Set());idx.get(a)!.add(k.id);}}return{idx,byId};},[degisimKayitlari]);
 const eslesen=(p:any)=>{const ids=degisimIndex.idx.get(anahtar(prop(p,"LOKASYON_I")));return ids?Array.from(ids).map(id=>degisimIndex.byId.get(id)).filter(Boolean) as DegisimKaydi[]:[];};
 const veriyiKur=(x:any,ad:string)=>{const a=ayir(x),kok=trafosuzBinalar(a.nokta.features,a.bina.features);pointData.current=a.nokta;kokData.current={type:"FeatureCollection",features:kok};setDosyaAdi(ad);setVeriHazir(true);setDurum(`${a.nokta.features.length.toLocaleString("tr-TR")} OG/AG trafo • ${kok.length.toLocaleString("tr-TR")} trafosuz KÖK`);setHata("");};
 const zipOku=async(blob:Blob,ad:string)=>{if(!window.shp)throw new Error("SHP okuyucu hazır değil");setDurum("Trafo ve KÖK envanteri hazırlanıyor...");veriyiKur(await window.shp(await blob.arrayBuffer()),ad);};
 async function oturumBilgisi(){if(!supabase)return{session:null,admin:false};const {data:{session}}=await supabase.auth.getSession();if(!session)return{session:null,admin:false};const {data:profil}=await supabase.from("app_users").select("role").eq("id",session.user.id).maybeSingle();const admin=profil?.role==="admin";setAdminMi(admin);return{session,admin};}
 async function merkezeAktar(blob:Blob,sessToken?:string){const token=sessToken||((await oturumBilgisi()).session?.access_token||"");if(!token)throw new Error("Admin oturumu gerekli.");const r=await fetch("/api/harita-envanter",{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/zip"},body:blob});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j?.error||"Merkezi envanter kaydedilemedi.");setMerkezi(true);}
 useEffect(()=>{let kapandi=false;(async()=>{setDegisimYukleniyor(true);try{if(!supabase)return;const {data,error}=await supabase.from("trafo_degisim").select("id,trafo_id,lokasyon_id,tr,tarih").order("tarih",{ascending:false});if(error)throw error;if(!kapandi)setDegisimKayitlari((data||[]) as DegisimKaydi[]);}catch(e:any){if(!kapandi)setHata(e.message);}finally{if(!kapandi)setDegisimYukleniyor(false);}})();oturumBilgisi().catch(()=>{});return()=>{kapandi=true;};},[supabase]);
 useEffect(()=>{let kapandi=false;const baslat=async()=>{try{if(!document.getElementById("leaflet-css-trafo")){const l=document.createElement("link");l.id="leaflet-css-trafo";l.rel="stylesheet";l.href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css";document.head.appendChild(l);}await Promise.all([scriptYukle("leaflet-js-trafo","https://unpkg.com/leaflet@1.9.4/dist/leaflet.js",()=>!!window.L),scriptYukle("shpjs-trafo","https://unpkg.com/shpjs@6.1.0/dist/shp.js",()=>!!window.shp)]);if(kapandi||!mapEl.current)return;const L=window.L,map=L.map(mapEl.current,{zoomControl:true,preferCanvas:true,renderer:L.canvas({padding:.5,tolerance:12})}).setView([39.65,27.9],9);tileLayer.current=L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:20}).addTo(map);mapRef.current=map;setHazir(true);let merkezVar=false;try{const r=await fetch("/api/harita-envanter",{cache:"no-store"});if(r.ok){const blob=await r.blob();await zipOku(blob,"Merkezi trafo envanteri");setMerkezi(true);merkezVar=true;try{await kaydetBlob(blob);}catch{}}}catch{}if(!merkezVar){const eski=await okuBlob().catch(()=>undefined);if(eski)await zipOku(eski,"Bu cihazdaki envanter");}}catch(e:any){if(!kapandi)setHata(e?.message||"Harita yüklenemedi");}};baslat();return()=>{kapandi=true;if(mapRef.current){mapRef.current.remove();mapRef.current=null;}};},[supabase]);
 useEffect(()=>{if(!hazir||!mapRef.current||!window.L)return;const L=window.L,map=mapRef.current;if(tileLayer.current)map.removeLayer(tileLayer.current);tileLayer.current=(haritaTipi==="uydu"?L.tileLayer("https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",{maxZoom:19}):L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:20})).addTo(map);tileLayer.current.bringToBack?.();},[haritaTipi,hazir]);
 useEffect(()=>{if(!hazir||!veriHazir||!mapRef.current||!window.L||!pointData.current||!kokData.current)return;const L=window.L,map=mapRef.current;if(pointLayer.current)map.removeLayer(pointLayer.current);if(buildingLayer.current)map.removeLayer(buildingLayer.current);const q=arama.trim().toLocaleLowerCase("tr-TR"),fil=(f:GeoFeature)=>{const p=f.properties||{};if(ilce&&norm(prop(p,"ILCE")).toLocaleLowerCase("tr-TR")!==ilce.toLocaleLowerCase("tr-TR"))return false;return !q||Object.values(p).some(v=>norm(v).toLocaleLowerCase("tr-TR").includes(q));};const normal=pointData.current.features.filter(f=>fil(f)&&(!sadeceDegisen||eslesen(f.properties).length>0)),kok=kokData.current.features.filter(fil);setNoktaSayisi(normal.length);setBinaSayisi(kok.length);let e=0,t=0,c=0;for(const f of pointData.current.features.filter(fil)){const n=eslesen(f.properties).length;if(n){e++;n===1?t++:c++;}}setEslesenSayisi(e);setTekDegisimSayisi(t);setCokDegisimSayisi(c);if(binaAcik&&!sadeceDegisen)buildingLayer.current=L.geoJSON({type:"FeatureCollection",features:kok},{style:()=>({color:"#0369a1",weight:3,fillColor:"#38bdf8",fillOpacity:.4}),onEachFeature:(f:any,l:any)=>l.bindPopup(kokPopup(f.properties||{}))}).addTo(map);if(noktaAcik)pointLayer.current=L.geoJSON({type:"FeatureCollection",features:normal},{pointToLayer:(f:any,ll:any)=>{const n=eslesen(f.properties).length;return L.circleMarker(ll,{radius:8,color:"#fff",weight:4,fillColor:n>1?"#a855f7":n===1?"#10b981":"#f97316",fillOpacity:1});},onEachFeature:(f:any,l:any)=>{const k=eslesen(f.properties).sort((a,b)=>String(b.tarih||"").localeCompare(String(a.tarih||"")));l.bindPopup(noktaPopup(f.properties,k.length,k[0]?.tarih||null));}}).addTo(map);},[hazir,veriHazir,ilce,arama,noktaAcik,binaAcik,sadeceDegisen,degisimKayitlari]);
 const adminGuncelle=async(e:ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];e.target.value="";if(!f)return;setEnvanterIslem(true);try{await zipOku(f,"Merkezi trafo envanteri");await merkezeAktar(f);await kaydetBlob(f);setDurum("Merkezi envanter güncellendi");}catch(err:any){setHata(err.message);}finally{setEnvanterIslem(false);}};
 const tumunuGoster=()=>{setIlce("");setArama("");setSadeceDegisen(false);};const toplam=noktaSayisi+binaSayisi;
 return <div className="space-y-4"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Kart ikon="⚡" baslik="OG/AG TRAFOLAR" deger={veriHazir?String(noktaSayisi):"—"} alt="Haritada görünen trafo"/><Kart ikon="🕘" baslik="DEĞİŞİM GÖRMÜŞ" deger={veriHazir&&!degisimYukleniyor?String(eslesenSayisi):"—"} alt={`${tekDegisimSayisi} tek • ${cokDegisimSayisi} çoklu değişim`}/><Kart ikon="🏢" baslik="TRAFOSUZ KÖK" deger={veriHazir?String(binaSayisi):"—"} alt="İçinde OG/AG trafo bulunmayan bina"/><Kart ikon="📍" baslik="İLÇE" deger={ilce||"Tümü"} alt="Aktif harita filtresi"/></div><div className="rounded-2xl border border-slate-200 bg-white p-4"><div className="flex justify-between"><div><b>🗺️ Trafo & KÖK Envanteri</b><div className="text-xs text-slate-500">{dosyaAdi} • {durum} • {degisimKayitlari.length} değişim kaydı</div></div>{adminMi&&<label className="cursor-pointer rounded-xl bg-blue-600 px-4 py-2 text-xs font-black text-white">☁ {envanterIslem?"Güncelleniyor...":"Envanteri Güncelle"}<input type="file" accept=".zip" onChange={adminGuncelle} className="hidden"/></label>}</div>{veriHazir&&<><div className="my-3 border-t"/><div className="flex flex-wrap gap-2"><select value={ilce} onChange={e=>setIlce(e.target.value)} className="rounded-xl border px-3 py-2"><option value="">Tüm İlçeler</option>{ILCE_LISTESI.map(x=><option key={x}>{x}</option>)}</select><input value={arama} onChange={e=>setArama(e.target.value)} placeholder="Trafo/KÖK ara..." className="min-w-[260px] flex-1 rounded-xl border px-3 py-2"/><button onClick={tumunuGoster} className="rounded-xl border px-3 py-2">Filtreyi Temizle</button></div><div className="mt-3 flex flex-wrap gap-2"><button onClick={()=>setNoktaAcik(v=>!v)} className="rounded-xl border px-3 py-2 text-xs font-black">⚡ OG/AG Trafolar ({noktaSayisi})</button><button onClick={()=>setBinaAcik(v=>!v)} className="rounded-xl border border-sky-200 bg-sky-50 px-3 py-2 text-xs font-black text-sky-700">🏢 Trafosuz KÖK ({binaSayisi})</button><button onClick={()=>setSadeceDegisen(v=>!v)} className="rounded-xl border px-3 py-2 text-xs font-black">🕘 {sadeceDegisen?"Tüm Trafoları Göster":"Sadece Değişim Yapılanlar"}</button><button onClick={()=>setHaritaTipi(x=>x==="standart"?"uydu":"standart")} className="rounded-xl border px-3 py-2 text-xs font-black">{haritaTipi==="standart"?"🛰️ Uydu Görünümü":"🗺️ Standart Harita"}</button><span className="ml-auto text-xs text-slate-400">Görünen toplam: {toplam}</span></div></>}</div>{hata&&<div className="rounded-xl bg-red-50 p-3 text-red-700">{hata}</div>}<div className="overflow-hidden rounded-2xl border bg-white"><div className="px-4 py-3 font-black">Balıkesir Trafo & KÖK Haritası</div><div ref={mapEl} className="h-[72vh] min-h-[580px] w-full"/></div></div>;
}
function Kart({ikon,baslik,deger,alt}:{ikon:string;baslik:string;deger:string;alt:string}){return <div className="rounded-2xl border bg-white p-4"><div className="text-xs font-black text-slate-400">{ikon} {baslik}</div><div className="text-xl font-black">{deger}</div><div className="text-[10px] text-slate-400">{alt}</div></div>;}