import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
export const runtime="nodejs"; export const dynamic="force-dynamic";
const BUCKET="trafo-yedekler";
function clients(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL,anon=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!anon||!key)throw new Error("Supabase sunucu ortam değişkenleri eksik.");return {auth:createClient(url,anon,{auth:{persistSession:false,autoRefreshToken:false}}),db:createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}})}}
async function admin(req:NextRequest){const {auth,db}=clients(),a=req.headers.get("authorization")||"",token=a.startsWith("Bearer ")?a.slice(7):"";if(!token)throw Object.assign(new Error("Oturum bulunamadı."),{status:401});const {data,error}=await auth.auth.getUser(token);if(error||!data.user)throw Object.assign(new Error("Oturum doğrulanamadı."),{status:401});const {data:r,error:re}=await db.from("app_users").select("role").eq("id",data.user.id).maybeSingle();if(re)throw new Error("Kullanıcı yetkisi okunamadı: "+re.message);if(!r||r.role!=="admin")throw Object.assign(new Error("Yalnızca yönetici sunucu yedeği alabilir."),{status:403});return db}
async function all(db:any){const out:any[]=[];const {data:years}=await db.storage.from(BUCKET).list("otomatik",{limit:100});for(const y of years||[]){if(!/^\d{4}$/.test(y.name))continue;const {data:months}=await db.storage.from(BUCKET).list(`otomatik/${y.name}`,{limit:20});for(const m of months||[]){if(!/^\d{2}$/.test(m.name))continue;const {data:files}=await db.storage.from(BUCKET).list(`otomatik/${y.name}/${m.name}`,{limit:100,sortBy:{column:"created_at",order:"desc"}});for(const f of files||[])if(f.name.endsWith(".json"))out.push({...f,path:`otomatik/${y.name}/${m.name}/${f.name}`})}}out.sort((a,b)=>String(b.created_at||b.updated_at||"").localeCompare(String(a.created_at||a.updated_at||"")));return out}
async function backup(db:any,source:"manual"|"automatic"="manual"){const [{data:k,error:e1},{data:a,error:e2},{data:s,error:e3},{data:l,error:e4}]=await Promise.all([db.from("trafo_degisim").select("*").order("id"),db.from("trafo_form_arsivi").select("*").order("created_at"),db.from("drive_sync_logs").select("*").order("created_at",{ascending:false}).limit(500),db.from("trafo_audit_log").select("*").order("created_at",{ascending:false}).limit(500)]);if(e1||e2||e3||e4)throw new Error("Yedek verileri okunamadı.");const n=new Date(),p=(x:number)=>String(x).padStart(2,"0"),stamp=`${n.getUTCFullYear()}-${p(n.getUTCMonth()+1)}-${p(n.getUTCDate())}-${p(n.getUTCHours())}${p(n.getUTCMinutes())}${p(n.getUTCSeconds())}`,path=`otomatik/${n.getUTCFullYear()}/${p(n.getUTCMonth()+1)}/TRAFO-${source==="automatic"?"OTOMATIK":"MANUEL"}-${stamp}.json`,body=Buffer.from(JSON.stringify({backupType:"BALIKESIR_TRAFO_SERVER_BACKUP",source,exportedAt:n.toISOString(),trafo_degisim:k||[],trafo_form_arsivi:a||[],drive_sync_logs:s||[],audit_logs:l||[]},null,2));const {error}=await db.storage.from(BUCKET).upload(path,body,{contentType:"application/json",upsert:false});if(error)throw new Error("Yedek Storage hatası: "+error.message);const files=await all(db);for(const f of files.slice(12))await db.storage.from(BUCKET).remove([f.path]);return {path,count:Math.min(files.length,12)}}
export async function GET(req:NextRequest){try{const a=req.headers.get("authorization")||"",cron=process.env.CRON_SECRET||"";if(cron&&a===`Bearer ${cron}`){const {db}=clients(),r=await backup(db,"automatic");return NextResponse.json({ok:true,source:"automatic",...r})}const db=await admin(req),files=await all(db);return NextResponse.json({ok:true,count:files.length,last:files[0]||null})}catch(e:any){return NextResponse.json({error:e?.message||"Yedek durumu alınamadı."},{status:e?.status||500})}}
export async function POST(req:NextRequest){try{const db=await admin(req),r=await backup(db);return NextResponse.json({ok:true,...r})}catch(e:any){return NextResponse.json({error:e?.message||"Sunucu yedeği alınamadı."},{status:e?.status||500})}}
