import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
export const runtime="nodejs"; export const dynamic="force-dynamic";
const BUCKET="trafo-yedekler"; const KEEP=1;
function clients(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL,anon=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!anon||!key)throw new Error("Supabase sunucu ortam değişkenleri eksik.");return {auth:createClient(url,anon,{auth:{persistSession:false,autoRefreshToken:false}}),db:createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}})}}
async function admin(req:NextRequest){const {auth,db}=clients(),a=req.headers.get("authorization")||"",token=a.startsWith("Bearer ")?a.slice(7):"";if(!token)throw Object.assign(new Error("Oturum bulunamadı."),{status:401});const {data,error}=await auth.auth.getUser(token);if(error||!data.user)throw Object.assign(new Error("Oturum doğrulanamadı."),{status:401});const {data:r,error:re}=await db.from("app_users").select("role").eq("id",data.user.id).maybeSingle();if(re)throw new Error("Kullanıcı yetkisi okunamadı: "+re.message);if(!r||r.role!=="admin")throw Object.assign(new Error("Bu işlem yalnızca yöneticiye açıktır."),{status:403});return db}
async function all(db:any){const out:any[]=[];const {data:years,error:ye}=await db.storage.from(BUCKET).list("otomatik",{limit:100});if(ye)throw new Error("Yedek yılları okunamadı: "+ye.message);for(const y of years||[]){if(!/^\d{4}$/.test(y.name))continue;const {data:months,error:me}=await db.storage.from(BUCKET).list(`otomatik/${y.name}`,{limit:20});if(me)throw new Error("Yedek ayları okunamadı: "+me.message);for(const m of months||[]){if(!/^\d{2}$/.test(m.name))continue;const {data:files,error:fe}=await db.storage.from(BUCKET).list(`otomatik/${y.name}/${m.name}`,{limit:100,sortBy:{column:"created_at",order:"desc"}});if(fe)throw new Error("Yedek listesi okunamadı: "+fe.message);for(const f of files||[])if(f.name.endsWith(".json"))out.push({...f,path:`otomatik/${y.name}/${m.name}/${f.name}`})}}out.sort((a,b)=>String(b.created_at||b.updated_at||"").localeCompare(String(a.created_at||a.updated_at||"")));return out}
function sourceLabel(source:"manual"|"automatic"|"safety"){return source==="automatic"?"OTOMATIK":source==="safety"?"GUVENLIK":"MANUEL"}
async function backup(db:any,source:"manual"|"automatic"|"safety"="manual"){const [{data:k,error:e1},{data:a,error:e2},{data:s,error:e3},{data:l,error:e4}]=await Promise.all([db.from("trafo_degisim").select("*").order("id"),db.from("trafo_form_arsivi").select("*").order("created_at"),db.from("drive_sync_logs").select("*").order("created_at",{ascending:false}).limit(500),db.from("trafo_audit_log").select("*").order("created_at",{ascending:false}).limit(500)]);if(e1||e2||e3||e4)throw new Error("Yedek verileri okunamadı.");const n=new Date(),p=(x:number)=>String(x).padStart(2,"0"),stamp=`${n.getUTCFullYear()}-${p(n.getUTCMonth()+1)}-${p(n.getUTCDate())}-${p(n.getUTCHours())}${p(n.getUTCMinutes())}${p(n.getUTCSeconds())}`,path=`otomatik/${n.getUTCFullYear()}/${p(n.getUTCMonth()+1)}/TRAFO-${sourceLabel(source)}-${stamp}.json`,body=Buffer.from(JSON.stringify({backupType:"BALIKESIR_TRAFO_SERVER_BACKUP",version:2,source,exportedAt:n.toISOString(),trafo_degisim:k||[],trafo_form_arsivi:a||[],drive_sync_logs:s||[],audit_logs:l||[]},null,2));const {error}=await db.storage.from(BUCKET).upload(path,body,{contentType:"application/json",upsert:false});if(error)throw new Error("Yedek Storage hatası: "+error.message);const files=await all(db);for(const f of files.slice(KEEP)){const {error:de}=await db.storage.from(BUCKET).remove([f.path]);if(de)throw new Error("Eski yedek temizleme hatası: "+de.message)}return {path,count:Math.min(files.length,KEEP),created_at:n.toISOString()}}
function validPath(path:any){return typeof path==="string"&&path.startsWith("otomatik/")&&path.endsWith(".json")&&!path.includes("..")}
async function readBackup(db:any,path:string){if(!validPath(path))throw new Error("Geçersiz yedek yolu.");const {data,error}=await db.storage.from(BUCKET).download(path);if(error||!data)throw new Error("Yedek dosyası okunamadı: "+(error?.message||"Bilinmeyen hata"));const text=await data.text();let j:any;try{j=JSON.parse(text)}catch{throw new Error("Yedek JSON dosyası okunamadı.")}if(!Array.isArray(j.trafo_degisim)||!Array.isArray(j.trafo_form_arsivi))throw new Error("Seçilen dosya geçerli Trafo sunucu yedeği değil.");return j}
async function insertChunks(db:any,table:string,rows:any[]){for(let i=0;i<rows.length;i+=100){const {error}=await db.from(table).insert(rows.slice(i,i+100));if(error)throw new Error(`${table} geri yükleme hatası: ${error.message}`)}}
async function restore(db:any,path:string){const j=await readBackup(db,path);const safety=await backup(db,"safety");const delOrder=["trafo_form_arsivi","trafo_degisim","drive_sync_logs","trafo_audit_log"];for(const table of delOrder){const {error}=await db.from(table).delete().not("id","is",null);if(error)throw new Error(`${table} temizleme hatası: ${error.message}`)}await insertChunks(db,"trafo_degisim",j.trafo_degisim||[]);await insertChunks(db,"trafo_form_arsivi",j.trafo_form_arsivi||[]);await insertChunks(db,"drive_sync_logs",j.drive_sync_logs||[]);await insertChunks(db,"trafo_audit_log",j.audit_logs||[]);return {ok:true,restored:path,safetyBackup:safety.path,restoredAt:new Date().toISOString(),summary:{trafo:(j.trafo_degisim||[]).length,arsiv:(j.trafo_form_arsivi||[]).length}}}
export async function GET(req:NextRequest){try{const a=req.headers.get("authorization")||"",cron=process.env.CRON_SECRET||"";if(cron&&a===`Bearer ${cron}`){const {db}=clients(),r=await backup(db,"automatic");return NextResponse.json({ok:true,source:"automatic",...r})}const db=await admin(req),files=await all(db);return NextResponse.json({ok:true,count:files.length,retention:KEEP,last:files[0]||null,backups:files.map(f=>({name:f.name,path:f.path,created_at:f.created_at,updated_at:f.updated_at,size:f.metadata?.size||null}))})}catch(e:any){return NextResponse.json({error:e?.message||"Yedek durumu alınamadı."},{status:e?.status||500})}}
export async function POST(req:NextRequest){try{const db=await admin(req);let body:any={};try{body=await req.json()}catch{}if(body.action==="restore"){if(body.confirm!=="GERI YUKLE")return NextResponse.json({error:"Geri yükleme onayı geçersiz."},{status:400});return NextResponse.json(await restore(db,body.path))}const r=await backup(db,"manual");return NextResponse.json({ok:true,...r})}catch(e:any){return NextResponse.json({error:e?.message||"Sunucu yedeği işlemi başarısız."},{status:e?.status||500})}}
